services:

  mza-agent:
    image: microzaccess/mza-agent:2.1.10
    container_name: mza-agent
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./shared/.config/cosgrid/config.json:/home/dockeruser/.config/cosgrid/config.json
      - /home/mza_connecter_id.json:/home/mza_connecter_id.json:ro
      - ./shared/service.log:/var/log/cosgrid/service.log
      - ./shared/cosgrid-microzaccess.log:/var/log/cosgrid/cosgrid-microzaccess.log 
    networks:
      cosgrid-net:
        ipv4_address: 172.28.0.2

  ztun-watcher:
    image: microzaccess/ztun-watcher:2.1.10
    container_name: ztun-watcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE  
      - DAC_OVERRIDE 
    devices:
      - /dev/net/tun
    network_mode: "service:mza-agent"
    pid: "service:mza-agent"

  logtrimmer:
    image: microzaccess/logtrimmer:2.1.10
    container_name: logtrimmer
    volumes:
      - ./mza-agent/shared/service.log:/var/log/cosgrid/service.log
      - ./mza-agent/shared/cosgrid-microzaccess.log:/var/log/cosgrid/cosgrid-microzaccess.log 
    networks:
      cosgrid-net:
        ipv4_address: 172.28.0.4

  fluent-bit:
    image: microzaccess/fluent-bit:2.1.10
    container_name: fluent-bit
    volumes:
      - /shared/service.log:/var/log/cosgrid
      - /shared/cosgrid-microzaccess.log:/var/log/cosgrid 
    networks:
      cosgrid-net:
        ipv4_address: 172.28.0.5

  squid-proxy:
    image: microzaccess/proxy:1.0
    container_name: proxy
    depends_on:
      - mza-agent
    # volumes:
    #   - ./shared/proxy_logs:/var/log/squid
    network_mode: "service:mza-agent"
    pid: "service:mza-agent" 

  redis-service:
    image: microzaccess/redis-service:appc
    container_name: redis-service
    volumes:
      - ./shared/.config/cosgrid/config.json:/home/.config/cosgrid/config.json
      - /home/mza_connecter_id.json:/home/mza_connecter_id.json:ro
      - /etc/ssl/certs:/etc/ssl/certs
    network_mode: "service:mza-agent"
    restart: unless-stopped

# Define the shared custom bridge network
networks:
  cosgrid-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16