version: '3.8'

services:

  mza-agent:
    image: microzaccess/mza-agent:2.1.10
    container_name: mza-agent
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./shared/.config/cosgrid:/home/root/.config/cosgrid:ro
      - /home/mza_connecter_id.json:/home/mza_connecter_id.json:ro
      - /shared/service.log:/var/log/cosgrid
      - /shared/cosgrid-microzaccess.log:/var/log/cosgrid 
    networks:
      cosgrid-net:
        ipv4_address: 172.28.0.2

  ztun-watcher:
    image: microzaccess/ztun-watcher:2.1.10
    container_name: ztun-watcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_NICE  # Add this
      - DAC_OVERRIDE 
    devices:
      - /dev/net/tun
    network_mode: "service:mza-agent"
    pid: "service:mza-agent"

  logtrimmer:
    image: microzaccess/logtrimmer:2.1.10
    container_name: logtrimmer
    volumes:
      - /shared/service.log:/var/log/cosgrid
      - /shared/cosgrid-microzaccess.log:/var/log/cosgrid 
    networks:
      cosgrid-net:
        ipv4_address: 172.28.0.4

  fluent-bit:
    image: microzaccess/fluent-bit:2.1.10
    container_name: fluent-bit
    volumes:
      - /shared/service.log:/var/log/cosgrid
      - /shared/cosgrid-microzaccess.log:/var/log/cosgrid 
    networks:
      cosgrid-net:
        ipv4_address: 172.28.0.5

# Define the shared custom bridge network
networks:
  cosgrid-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
